[project]
name = "func-dataset-sanitizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=3.6.0",
    "jsondiff>=2.2.1",
    "openai>=1.82.0",
    "pydantic>=2.11.5",
]
